#!/usr/bin/env python3
"""Emit cmake/decomp_sources.cmake: the decomp translation units the port compiles.

Scope: every .c/.cpp under decomp/src except the SDK, MSL, MetroTRK and the
OdemuExi2 debugger link. JSystem and THPPlayer .c files are C++ (their MWCC
libraries pass -lang=c++); other .c files stay C. Units that MWCC built with
-prefix SMS.mch get the game PCH force-included.
"""
import os, re, sys

root = os.path.abspath(sys.argv[1] if len(sys.argv) > 1 else os.path.join(os.path.dirname(__file__), '..', 'decomp'))
out = sys.argv[2] if len(sys.argv) > 2 else os.path.join(os.path.dirname(__file__), '..', 'cmake', 'decomp_sources.cmake')
EXCLUDE = ('dolphin/', 'PowerPC_EABI_Support/', 'TRK_MINNOW_DOLPHIN/', 'OdemuExi2/')

cfg = open(os.path.join(root, 'configure.py')).read()
pch = set(re.findall(r'PCHObject\(\s*[^,]+,\s*"([^"]+)"', cfg))

cxx, c, pchs = [], [], []
src = os.path.join(root, 'src')
for d, _, files in os.walk(src):
    for f in files:
        if not f.endswith(('.c', '.cpp')):
            continue
        rel = os.path.relpath(os.path.join(d, f), src).replace(os.sep, '/')
        if rel.startswith(EXCLUDE):
            continue
        if f.endswith('.c') and not rel.startswith(('JSystem/', 'THPPlayer/')):
            c.append(rel)
        else:
            cxx.append(rel)
        if rel in pch:
            pchs.append(rel)

def block(name, items):
    return 'set(%s\n%s\n)\n' % (name, '\n'.join('  ${SMS_DECOMP}/src/' + i for i in sorted(items)))

with open(out, 'w') as fp:
    fp.write('# Generated by tools/gen_sources.py -- do not edit.\n')
    fp.write(block('SMS_DECOMP_CXX_SOURCES', cxx))
    fp.write(block('SMS_DECOMP_C_SOURCES', c))
    fp.write(block('SMS_DECOMP_PCH_SOURCES', pchs))
print('%d C++ units, %d C units, %d with PCH (%d PCH names in configure.py)' % (len(cxx), len(c), len(pchs), len(pch)), file=sys.stderr)
