# Applies decomp-patches/*.patch (unified diffs against decomp/, -p1) to copies
# of the touched files in ${CMAKE_BINARY_DIR}/patched, at configure time.
# Patched sources replace their originals in the source lists; patched headers
# live under patched/include, which is searched before decomp/include.
set(SMS_PATCH_ROOT ${CMAKE_BINARY_DIR}/patched)
set(SMS_PATCHED_INCLUDE_DIR ${SMS_PATCH_ROOT}/include)
file(GLOB SMS_PATCHES ${CMAKE_CURRENT_SOURCE_DIR}/decomp-patches/*.patch)
list(SORT SMS_PATCHES)
file(REMOVE_RECURSE ${SMS_PATCH_ROOT})
file(MAKE_DIRECTORY ${SMS_PATCHED_INCLUDE_DIR})
set(_touched "")
foreach(p ${SMS_PATCHES})
  set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS ${p})
  file(STRINGS ${p} _hdrs REGEX "^\\+\\+\\+ b/")
  foreach(h ${_hdrs})
    string(REGEX REPLACE "^\\+\\+\\+ b/([^\t ]+).*" "\\1" f "${h}")
    if(NOT EXISTS ${SMS_PATCH_ROOT}/${f})
      get_filename_component(d ${SMS_PATCH_ROOT}/${f} DIRECTORY)
      file(MAKE_DIRECTORY ${d})
      file(COPY_FILE ${SMS_DECOMP}/${f} ${SMS_PATCH_ROOT}/${f})
      list(APPEND _touched ${f})
    endif()
  endforeach()
  execute_process(COMMAND patch -p1 --quiet -d ${SMS_PATCH_ROOT} -i ${p}
                  RESULT_VARIABLE rc)
  if(NOT rc EQUAL 0)
    message(FATAL_ERROR "port patch failed to apply: ${p}")
  endif()
endforeach()
foreach(f ${_touched})
  if(f MATCHES "^src/")
    foreach(lst SMS_DECOMP_CXX_SOURCES SMS_DECOMP_C_SOURCES SMS_DECOMP_PCH_SOURCES)
      list(FIND ${lst} ${SMS_DECOMP}/${f} idx)
      if(NOT idx EQUAL -1)
        list(REMOVE_AT ${lst} ${idx})
        list(INSERT ${lst} ${idx} ${SMS_PATCH_ROOT}/${f})
      endif()
    endforeach()
  endif()
endforeach()
list(LENGTH SMS_PATCHES _n)
message(STATUS "SMS port: ${_n} decomp patch(es) applied")
